### ISSUE TITLE
header 'Stamford Center' overflowing, not responsive. 

### ISSUE THREAD

**Issue by anascence** [stamford-syntax-club/stamfordcenter-frontend#3]
1. Just make it responsive again. !! on mobile veiw

**Comment by Lxkas** [comment]
Fixed [here](https://github.com/stamford-syntax-club/stamfordcenter-frontend/commit/3673f4cb9328d18cb78bed6c4a89ba138de5e25a#diff-18e0d4553c97cfc420e938ccafb4e3a688e782fa4512ba4ceae3e2a6f24c1987L40), thanks!
